### ISSUE TITLE
 Inquiry about support for iRODS softlinks

### ISSUE THREAD

**Issue by KKTRKKT** [cyverse/sftpgo-auth-irods#2]
Hello,

I am a user of the sftpgo-auth-irods module, and I would like to inquire about the support for iRODS softlinks. I am planning to raise an issue on GitHub regarding this matter.

My question is as follows:

Does the sftpgo-auth-irods module support iRODS softlinks? If so, are there any additional configurations required to use iRODS softlinks through the module?

As a user in need of assistance with this module, I would greatly appreciate any information regarding the support for iRODS softlinks.

Thank you for your attention.

**Comment by iychoi** [comment]
Hi,

The auth module is not responsible for iRODS data access. It only authenticates iRODS users. So you made the ticket on wrong repository. 

However, as I also am the author of SFTPGo iRODS module, I can answer. 
Currently, I have no plan to support soft links because it is little complicated.

1) If we assume that the softlink target is an iRODS data object or collection, linux `ln` command will not work as it does not know about iRODS directory hierarchy.
2) If we assume that the softlink target is a local file or directory, the path to target is not decisive. Because users can change file system mount path (where to mount iRODS user home collection on the local directory hierarchy), relative path may change. So the softlink will not be valid if user changes the mount path.

Hope this answers your question.
If you have suggestions about this, leave a ticket on [SFTPGo](https://github.com/cyverse/sftpgo) repository.

Thanks

**Comment by iychoi** [comment]
Just realized that there's no issue tracker available for SFTPGo repository.

If the question was related to SFTPGo, leave message here on sftpgo-auth-irods repository.
If the question was related to general iRODS file system client, leave a ticket on [iRODS FUSE Lite](https://github.com/cyverse/irodsfs) repo.
